//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kttaq2210900075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taqSinhVien
    {
        public string taqMaSV { get; set; }
        public string taqHoSV { get; set; }
        public string taqTenSV { get; set; }
        public Nullable<System.DateTime> taqNgaySinh { get; set; }
        public Nullable<bool> taqPhai { get; set; }
        public string taqPhone { get; set; }
        public string taqEmail { get; set; }
        public string taqMaKH { get; set; }
    }
}
